"""Deterministic shared-context Markdown rendering."""

from __future__ import annotations

from .models import ProjectFacts


AUTO_START = "<!-- aictx:auto:start -->"
AUTO_END = "<!-- aictx:auto:end -->"
MANUAL_START = "<!-- aictx:manual:start -->"
MANUAL_END = "<!-- aictx:manual:end -->"


class MarkerError(ValueError):
    """Raised when a managed Markdown file has unsafe markers."""


def _manual_content(existing: str | None) -> str:
    if existing is None:
        return "\n## Project memory\n\nRecord goals, architecture decisions, constraints, current state, and known issues here.\n"
    markers = (AUTO_START, AUTO_END, MANUAL_START, MANUAL_END)
    if any(existing.count(marker) != 1 for marker in markers):
        raise MarkerError("managed file must contain each marker exactly once")
    positions = [existing.index(marker) for marker in markers]
    if positions != sorted(positions):
        raise MarkerError("managed markers are out of order")
    start = positions[2] + len(MANUAL_START)
    end = positions[3]
    return existing[start:end]


def _automatic(facts: ProjectFacts) -> str:
    lines = [f"# {facts.project.name}", "", "## Detected facts", ""]
    lines.append(f"- Path: `{facts.project.relative_path}`")
    if facts.description:
        lines.append(f"- Description: {facts.description}")
    if facts.technologies:
        lines.append(f"- Technologies: {', '.join(facts.technologies)}")
    if facts.git_branch:
        status = "dirty" if facts.git_dirty else "clean"
        lines.append(f"- Git: `{facts.git_branch}` ({status})")
    if facts.directories:
        lines.append(f"- Directories: {', '.join(f'`{name}`' for name in facts.directories)}")
    if facts.commands:
        lines.extend(["", "### Commands", ""])
        lines.extend(f"- {name}: `{command}`" for name, command in facts.commands)
    lines.extend(["", "## Observation scope", ""])
    if facts.scanned_files:
        sources = ", ".join(f"`{path.as_posix()}`" for path in facts.scanned_files)
        lines.append(f"- Recognized metadata: {sources}")
    else:
        lines.append("- Recognized metadata: none")
    lines.append("- Git metadata: branch, HEAD, and working-tree state")
    lines.append("- Directory metadata: immediate child directory names")
    lines.extend(
        [
            "",
            "These detected facts cover only the inputs above; they are not a full source-code analysis.",
        ]
    )
    return "\n".join(lines).rstrip() + "\n"


def render_project_memory(facts: ProjectFacts, existing: str | None = None) -> str:
    manual = _manual_content(existing)
    return (
        f"{AUTO_START}\n{_automatic(facts)}{AUTO_END}\n\n"
        f"{MANUAL_START}{manual}{MANUAL_END}\n"
    )


def render_workspace(facts: list[ProjectFacts]) -> str:
    lines = ["# Workspace", "", "Load only the memory file for the project currently being changed.", ""]
    for item in sorted(facts, key=lambda value: value.project.relative_path):
        slug = slugify(item.project.name)
        lines.append(
            f"- [{item.project.name}](projects/{slug}.md) — `{item.project.relative_path}`"
        )
    return "\n".join(lines).rstrip() + "\n"


def render_chatgpt_project_context(
    facts: ProjectFacts, project_memory: str | None, global_context: str | None
) -> str:
    """Render a portable context file for a ChatGPT Project source upload.

    The file is deliberately a one-way handoff. It does not represent, read, or
    modify ChatGPT's saved memories; the workspace remains the source of truth.
    """

    manual = _manual_content(project_memory).strip()
    shared = (global_context or "").strip()
    lines = [
        f"# ChatGPT Project Context: {facts.project.name}",
        "",
        "> Generated by AI Context Kit from bounded workspace observations and user-maintained context.",
        "> Regenerate this file after meaningful project changes, then replace the uploaded copy in ChatGPT.",
        "",
        "## Use in ChatGPT",
        "",
        "1. Add this file to the matching ChatGPT Project as a source.",
        "2. Start task-specific chats inside that Project so they share this context.",
        "3. Treat this file as project guidance, not as a replacement for ChatGPT saved memory.",
        "",
        "Official references:",
        "",
        "- https://learn.chatgpt.com/docs/projects",
        "- https://learn.chatgpt.com/docs/customization/memories",
        "",
    ]
    if shared:
        lines.extend(["## Shared context", "", shared, ""])
    lines.extend(["## Project facts", "", _automatic(facts).strip(), ""])
    if manual:
        lines.extend(["## Project memory", "", manual, ""])
    lines.extend(
        [
            "## Freshness and scope",
            "",
            "- The automatic facts are limited to the observation scope shown above.",
            "- Read current repository files before making changes; this file is a handoff aid, not the authority.",
            "- Do not include secrets or private material that should not be uploaded to ChatGPT.",
        ]
    )
    return "\n".join(lines).rstrip() + "\n"


def slugify(value: str):
    slug = "".join(character.lower() if character.isalnum() else "-" for character in value)
    return "-".join(part for part in slug.split("-") if part) or "project"
